name: Run Jest Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ production ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.5.2
    - name: Install dependencies
      run: yarn
    - name: Run tests
      run: yarn test
